# Page settings

baseurl = "https://cv-asamo7.netlify.com/"
languageCode = "ca"
defaultContentLanguage = "ca"
title = "Albert Sancho CV"
theme = "hugo-orbit-theme"
#googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Albert Sancho CV"
    author = "Albert Sancho"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Albert Sancho"
        tagline = "Arquitecte TI"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel: 687045324"
        title = "687045324"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:asamo7@gmail.com"
        title = "asamo7@gmail.com"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/asamo7"
        title = "@asamo7"

        #[[params.contact.list]]
        #class = "website"
        #icon = "fa-globe"
        #url = "//portfoliosite.com"
        #title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/asancho/"
        title = "linkedin.com/in/asancho/"

        #[[params.contact.list]]
        #class = "github"
        #icon = "fa-github"
        #url = "//github.com/asamo7"
        #title = "github.com/asamo7"

    # Education section
    [params.education]
        enable = true
        title = "Titulacions"

        [[params.education.list]]
        degree = "Enginyeria tècnica en Informàtica de Sistemes"
        college = "FIB"
        dates = "1998 - 2004"

        [[params.education.list]]
        degree = "Enginyeria Informàtica (segon cicle)"
        college = "UOC"
        dates = "2005 - no finalitzat"

        [[params.education.list]]
        degree = "SCJP (Sun Certified Java Programmer)"
        college = "Sun microsystems"
        dates = "2008"

        [[params.education.list]]
        degree = "SCWCD (Sun Certified Web Component Developer)"
        college = "Sun microsystems"
        dates = "2009"

        #[[params.education.list]]
        #degree = "M101JS (MongoDB for Node.js Developers)"
        #college = "MongoDB University"
        #dates = "2013"

        [[params.education.list]]
        degree = "ITIL Foundation Certificate"
        college = "APMG International"
        dates = "2016"

        [[params.education.list]]
        degree = "Professional Scrum Master I"
        college = "Scrum.org"
        dates = "2017"

        #[[params.education.list]]
        #degree = "Microservices with Spring Cloud"
        #college = "Udemy"
        #dates = "2017"

        #[[params.education.list]]
        #degree = "Azure Architect Beginner"
        #college = "Microsoft"
        #dates = "2019"

        #[[params.education.list]]
        #degree = "Developing on AWS"
        #college = "CSUC"
        #dates = "2019"

        #[[params.education.list]]
        #degree = "Advanced Architecting on AWS"
        #college = "IT Institute"
        #dates = "2020"

        #[[params.education.list]]
        #degree = "Architecture Workshop"
        #college = "OutSystems"
        #dates = "2022"

    # Languages section
    [params.language]
        enable = true
        title = "Idiomes"

        [[params.language.list]]
        language = "Català"
        level = "Natiu"

        [[params.language.list]]
        language = "Castellà"
        level = "Natiu"

        [[params.language.list]]
        language = "Anglès"
        level = "Profesional"


    # Interests section
    [params.interests]
        enable = true
        title = "Aficions"

        [[params.interests.list]]
        interest = "Activitats en família"

        [[params.interests.list]]
        interest = "Esports i tecnologia"

        #[[params.interests.list]]
        #interest = "Tecnologia"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Perfil"
        summary = "Arquitecte amb prop de 20 anys d'experiència a l'àmbit tecnològic havent desenvolupat diferents funcions tant de gestió com tècniques. Responsable de l'ecosistema DevOps, plataforma LowCode, i arquitecte de referència del Grup Operatiu de Gestió Acadèmica i Docent a la UOC durant els darrers 4 anys. Apassionat de la tecnologia, sempre amb ganes d'aprendre i col·laborar per a l'èxit dels projectes."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "IT Architect"
        dates = "2019 - Actualitat"
        company = "UOC (Universitat Oberta de Catalunya)"
        details = "* Responsable de l'ecosistema DevOps i LowCode de la UOC, així com referent d'arquitectura del Grup Operatiu de Gestió Acadèmica i Docent. Com a projectes més destacats: Nou Sistema d'Avaluació Digital, Migració CPD a AWS, Emissió de Certificats Digitals i Nous Fòrums."

        [[params.jobs.list]]
        position = "Software & DevOps Architect"
        dates = "2012 - 2019"
        company = "openTrends, Barcelona"
        details = "* Responsable tecnològic de l’àrea d’arquitectura de TICxCAT en el manteniment, evolució i nous projectes desenvolupats pel CTTI. Suport a la definició de l'estratègia DevOps.\n* Des de 2016, responsable de la nova OT Suport Cloud destinada al suport tecnològic per al desplegament d‘aplicacions en entorns Cloud."

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "2007 - 2012"
        company = "openTrends, Barcelona"
        details = "* Responsable tècnic i funcional del projecte de Governança radioelèctrica per al CTTI.\n* Responsable tècnic i funcional dels projectes de Estadístiques anuals i Butlletí de conjuntura energètica de Catalunya per l’ICAEN.\n* Responsable tècnic i funcional del projecte Linneo per el Grupo Godó.\n* Suport tècnic al desenvolupament de projectes amb openFrame per Danone.\n* Evolució de l'aplicació SAMC (Plataforma d'enviament de trameses) amb el mòdul de signatura de correus ASF per la Diputació de Barcelona.\n* Anàlisi i desenvolupament del projecte SGTFNM (Sistema de Gestió de Títols de Família Nombrosa i Monoparental) pel Departament de Benestar Social i Família."

        [[params.jobs.list]]
        position = "Analista programador Java/JEE"
        dates = "2005 - 2007"
        company = "Atos Origin, Barcelona"
        details = "* Evolució/Manteniment del Framework JEE Canigó de la Generalitat de Catalunya.\n* Anàlisi i desenvolupament dels projectes Gestió Acadèmica per l’Escola de Policia en Canigó i del Nou Model d’OC’s i ITV’s del Departament d'Indústria de la Generalitat."

        [[params.jobs.list]]
        position = "Programador Java/JEE"
        dates = "2005"
        company = "Informàtica Mèdica SL, Barcelona"
        details = "* Desenvolupament de l’aplicació JEE CAPSIS per Centres d’assistència primària."

        [[params.jobs.list]]
        position = "Programador junior Java/JEE"
        dates = "2003 - 2005"
        company = "Eina Informàtica, Barcelona"
        details = "* Col·laboració en el desenvolupament d'una eina CASE distribuïda com a projecte de final de carrera."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projectes"
        intro = "A continuació es mostra un resum dels projectes més rellevants en els que he participat darrerament:"

        [[params.projects.list]]
        title = "Nou Sistema d'Avaluació Digital"
        #url = "https://github.com/aerohub/hugrid"
        tagline = "Arran de la pandèmia la UOC va haver d'implantar en temps rècord un nou sistema d'avaluació digital que permetés al 100% dels estudiants fer els exàmens finals de forma telemàtica"

        [[params.projects.list]]
        title = "Migració CPD a AWS"
        #url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Migració de tots els sistemes d'informació existents al CPD de Castelldefels a AWS."

        [[params.projects.list]]
        title = "Emissió de Certificats Digitals"
        #url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Primera aplicació desenvolupada en una plataforma LowCode a la UOC, la qual permet la sol·licitud de certificats digitals per part dels estudiants i l'automatització en el procés de generació a partir d'unes plantilles predefinides."

        [[params.projects.list]]
        title = "Nous Fòrums"
        #url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Implantació d'un nou sistema de fòrums el qual substitueix l'anterior amb més de 20 anys d'història. També desenvolupat sobre plataforma LowCode."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Coneixements"

        [[params.skills.list]]
        skill = "Java: Spring Framework, JHipster, JEE, Struts"
        level = "95%"

        [[params.skills.list]]
        skill = "Servidors d'aplicacions: Tomcat, Jetty, JBoss, Weblogic"
        level = "95%"

        [[params.skills.list]]
        skill = "Servidors web: Apache, NGinx"
        level = "95%"

        [[params.skills.list]]
        skill = "Patrons Arquitectura: SOA, Microserveis, REST API, WS, MVC"
        level = "95%"

        [[params.skills.list]]
        skill = "Seguretat: JWT (Json Web Token), SAML, OAuth"
        level = "95%"

        [[params.skills.list]]
        skill = "CI: Jenkins, GitHub Actions, AWS CodePipeline, Go"
        level = "95%"

        [[params.skills.list]]
        skill = "SCM: Git, SVN, CVS"
        level = "95%"

        [[params.skills.list]]
        skill = "Plataformes Cloud: AWS, Azure, Openshift, IBM Bluemix"
        level = "95%"

        [[params.skills.list]]
        skill = "Contenidors: Docker, ECS, Swarm, Kubernetes"
        level = "95%"

        [[params.skills.list]]
        skill = "Funcions: AWS Lambda"
        level = "95%"

        [[params.skills.list]]
        skill = "Infraestructura com a codi (IaC): Terraform, Serverless"
        level = "95%"

        [[params.skills.list]]
        skill = "Serveis: PaaS (Cloud Foundry), DBaaS (Compose, Atlas), SaaS (Algolia)"
        level = "95%"

        [[params.skills.list]]
        skill = "Gestió de projectes: Atlassian JIRA, Redmine"
        level = "95%"

        [[params.skills.list]]
        skill = "Formularis electrònics: Adobe Experience Manager, Orbeon, Form.io"
        level = "95%"

        [[params.skills.list]]
        skill = "LowCode: OutSystems, AWS HoneyCode"
        level = "95%"

        [[params.skills.list]]
        skill = "Metodologies: SCRUM, Agile, ITIL"
        level = "70%"

        [[params.skills.list]]
        skill = "Bases de dades: AWS RDS, AWS DynamoDB, MySQL, Oracle, PostgreSQL, SQL Server, MongoDB"
        level = "70%"

        [[params.skills.list]]
        skill = "Traces i monitorització: AWS CloudWatch, Elasticsearch, Zipkin, Prometheus"
        level = "70%"

        [[params.skills.list]]
        skill = "Anàlisi de qualitat/seguretat: Sonar, Kiuwan, Fortify, OWASP ZAP, Anchore i DependencyCheck"
        level = "70%"

        [[params.skills.list]]
        skill = "Web: HTML5, CSS3, Javascript, JQuery"
        level = "70%"

        [[params.skills.list]]
        skill = "Generadors de webs estàtiques: Hugo"
        level = "70%"

        [[params.skills.list]]
        skill = "Altres llenguatges: NodeJS, Golang, Python"
        level = "50%"

        [[params.skills.list]]
        skill = "Frontend frameworks: Angular, React, Vue"
        level = "50%"

        [[params.skills.list]]
        skill = "Mobile: React Native (Android, iOS)"
        level = "30%"

    # Recommendations section
    [params.recommendations]
        enable = false
        icon = "fa-rocket"
        title = "Recomanacions"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
