# Page settings

baseurl = "https://cv-asamo7.netlify.com/"
languageCode = "ca"
defaultContentLanguage = "ca"
title = "Albert Sancho CV"
theme = "hugo-orbit-theme"
#googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Albert Sancho CV"
    author = "Albert Sancho"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Albert Sancho"
        tagline = "Arquitecte TI"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel: 687045324"
        title = "687045324"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: asamo7@gmail.com"
        title = "asamo7@gmail.com"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/asamo7"
        title = "@asamo7"

        #[[params.contact.list]]
        #class = "website"
        #icon = "fa-globe"
        #url = "//portfoliosite.com"
        #title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/asancho/"
        title = "linkedin.com/in/asancho/"

        #[[params.contact.list]]
        #class = "github"
        #icon = "fa-github"
        #url = "//github.com/asamo7"
        #title = "github.com/asamo7"

    # Education section
    [params.education]
        enable = true
        title = "Titulacions"

        [[params.education.list]]
        degree = "Enginyeria tècnica en Informàtica de Sistemes"
        college = "FIB"
        dates = "1998 - 2004"

        [[params.education.list]]
        degree = "Enginyeria Informàtica (segon cicle)"
        college = "UOC"
        dates = "2005 - no finalitzat"

        [[params.education.list]]
        degree = "SCJP (Sun Certified Java Programmer)"
        college = "Sun microsystems"
        dates = "2008"

        [[params.education.list]]
        degree = "SCWCD (Sun Certified Web Component Developer)"
        college = "Sun microsystems"
        dates = "2009"

        [[params.education.list]]
        degree = "M101JS (MongoDB for Node.js Developers)"
        college = "MongoDB University"
        dates = "2013"

        [[params.education.list]]
        degree = "ITIL Foundation Certificate"
        college = "APMG International"
        dates = "2016"

        [[params.education.list]]
        degree = "Professional Scrum Master I"
        college = "Scrum.org"
        dates = "2017"

        [[params.education.list]]
        degree = "Microservices with Spring Cloud"
        college = "Udemy"
        dates = "2017"

    # Languages section
    [params.language]
        enable = true
        title = "Idiomes"

        [[params.language.list]]
        language = "Català"
        level = "Natiu"

        [[params.language.list]]
        language = "Castellà"
        level = "Natiu"

        [[params.language.list]]
        language = "Anglès"
        level = "Profesional"


    # Interests section
    [params.interests]
        enable = true
        title = "Aficions"

        [[params.interests.list]]
        interest = "Activitats en família"

        [[params.interests.list]]
        interest = "Esports"

        [[params.interests.list]]
        interest = "Tecnologia"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Perfil"
        summary = "Arquitecte amb més de 15 anys d'experiència havent desenvolupat diferents funcions tant de gestió com tècniques. Responsable de les oficines tècniques de Solucions d'Arquitectura i Suport Cloud d'Arquitectura CTTI durant els 6 darrers anys. Apassionat de la tecnologia, sempre amb ganes d'aprendre i col·laborar per a l'èxit dels projectes. Especialment interessat en els camps d'**arquitectura d'aplicacions, Cloud i DevOps**."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "IT Architect"
        dates = "2012 - Actualitat"
        company = "openTrends, Barcelona"
        details = "* Responsable tecnològic de l’àrea d’arquitectura de TICxCAT en el manteniment, evolució i nous projectes desenvolupats pel CTTI. Suport a la definició de l'estratègia DevOps.\n* Des de 2016, responsable de la nova OT Suport Cloud destinada al suport tecnològic per al desplegament d‘aplicacions en entorns Cloud."

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "2007 - 2012"
        company = "openTrends, Barcelona"
        details = "* Responsable tècnic i funcional del projecte de Governança radioelèctrica per al CTTI.\n* Responsable tècnic i funcional dels projectes de Estadístiques anuals i Butlletí de conjuntura energètica de Catalunya per l’ICAEN.\n* Responsable tècnic i funcional del projecte Linneo per el Grupo Godó.\n* Suport tècnic al desenvolupament de projectes amb openFrame per Danone.\n* Evolució de l'aplicació SAMC (Plataforma d'enviament de trameses) amb el mòdul de signatura de correus ASF per la Diputació de Barcelona.\n* Anàlisi i desenvolupament del projecte SGTFNM (Sistema de Gestió de Títols de Família Nombrosa i Monoparental) pel Departament de Benestar Social i Família."

        [[params.jobs.list]]
        position = "Analista programador Java/JEE"
        dates = "2005 - 2007"
        company = "Atos Origin, Barcelona"
        details = "* Evolució/Manteniment del Framework JEE Canigó de la Generalitat de Catalunya.\n* Anàlisi i desenvolupament dels projectes Gestió Acadèmica per l’Escola de Policia en Canigó i del Nou Model d’OC’s i ITV’s del Departament d'Indústria de la Generalitat."

        [[params.jobs.list]]
        position = "Programador Java/JEE"
        dates = "2005"
        company = "Informàtica Mèdica SL, Barcelona"
        details = "* Desenvolupament de l’aplicació JEE CAPSIS per Centres d’assistència primària."

        [[params.jobs.list]]
        position = "Programador junior Java/JEE"
        dates = "2003 - 2005"
        company = "Eina Informàtica, Barcelona"
        details = "* Col·laboració en el desenvolupament d'una eina CASE distribuïda com a projecte de final de carrera."

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projectes"
        intro = "A continuació es mostra un resum dels projectes més rellevants en els que he participat:"

        [[params.projects.list]]
        title = "Hugrid"
        #url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Coneixements"

        [[params.skills.list]]
        skill = "Java: JEE, Spring Framework, Struts, JHipster"
        level = "98%"

        [[params.skills.list]]
        skill = "Patrons Arquitectura: SOA, Microserveis, REST API, WS, MVC"
        level = "98%"

        [[params.skills.list]]
        skill = "Seguretat: JWT (Json Web Token), SAML 2.0"
        level = "98%"

        [[params.skills.list]]
        skill = "CI: Jenkins, Go"
        level = "98%"

        [[params.skills.list]]
        skill = "SCM: Git, SVN, CVS"
        level = "98%"

        [[params.skills.list]]
        skill = "Plataformes Cloud: IBM Bluemix, Azure, Openshift"
        level = "98%"

        [[params.skills.list]]
        skill = "Contenidors: Docker, Swarm, Kubernetes"
        level = "98%"

        [[params.skills.list]]
        skill = "Serveis: PaaS (Cloud Foundry), DBaaS (Compose, Atlas), SaaS (Algolia)"
        level = "98%"

        [[params.skills.list]]
        skill = "Gestió de projectes: Atlassian JIRA, Redmine"
        level = "98%"

        [[params.skills.list]]
        skill = "Formularis electrònics: Adobe Experience Manager, Orbeon, Form.io"
        level = "98%"

        [[params.skills.list]]
        skill = "Metodologies: SCRUM, Agile, ITIL"
        level = "95%"

        [[params.skills.list]]
        skill = "Servidors d'aplicacions: JBoss, Weblogic, Tomcat"
        level = "95%"

        [[params.skills.list]]
        skill = "Servidors web: Apache, NGinx"
        level = "95%"

        [[params.skills.list]]
        skill = "Bases de dades: MySQL, Oracle, PostgreSQL, SQL Server"
        level = "85%"

        [[params.skills.list]]
        skill = "Web: HTML5, CSS3, Javascript, JQuery"
        level = "85%"

        [[params.skills.list]]
        skill = "Generadors de webs estàtiques: Hugo"
        level = "75%"

        [[params.skills.list]]
        skill = "Angular"
        level = "60%"

        [[params.skills.list]]
        skill = "Altres llenguatges: NodeJS, Golang"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
