backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "content/uploads" # Media files will be stored in the repo under static/assets/images
public_folder: "/uploads" # The src attribute for uploaded media will begin with /assets/images
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "recommendations"
    label: "Recommendations"
    folder: "content/recommendations"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
    #  - {label: "Body", name: "body", widget: "markdown"}